version: 0.1.0
name: Serenity EHS
description: Environmental, Health, and Safety for the ServiceNow Platform
url: https://serenityehs.com
repository: https://github.com/serenity-ehs/serenity-ehs.github.io
timezone: America/Los_Angeles
twitter:
  username: serenity_ehs

logo: "/images/github.png"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
